DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app                             VARCHAR(50)        NOT NULL,
    uri                             VARCHAR(50)        NOT NULL,
    ip                              VARCHAR(50)        NOT NULL,
    request_timestamp               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);